# MCBDD 2022 Project

Noe Manzoni, June 2022

### Description of the tasks in our project and some more information:

Write a Rmarkdown/Jupyter report analysing data from the Drug Central database, raising your own scientific questions about drug-target associations and answering them with analysis.

my goal:\
I want to find the distribution of drug targets by target class of a specific drug. The drug I have chosen is „Chlorothiazed“.
In addition I want to use the whole database and explore its data, so that I can analyze our drug with a Jupyter Notebook using SQL on the postgreSQL file provided  by drugcenral:
https://drugcentral.org/ActiveDownload

#steps taken in our project:


-- set up of the environment to proceed with data analysis --

1.in Terminal
curl https://bootstrap.pypa.io/pip/2.7/get-pip.py | python3


2.in Jupyter Notebook
!pip install ipython-sql


3.installing postgresql with installer (windows)
https://www.enterprisedb.com/downloads/postgres-postgresql-downloads


4.go to server with entering following command in terminal:
psql -U nameOfTheServer


5.created a database called „drug“
postgres=# 	create database nameOfDatabase;


6.exit plsql
\q


7.import data from sql file got from https://drugcentral.org/ActiveDownload
and store the data to directory. After downloading it, import data into database with command:
psql nameOfTheDatabase nameOfTheServer > 20210613-ChEMBL-drugs-since-2012-UniProt


8.executed further installing commands in jupyter
pip install sqlalchemy psycopg2


9.connected to db with code in Jupyter
import sqlalchemy
sqlalchemy.create_engine('postgresql://postgres:dario2022@localhost/test') ('postgresql://username:password@host:port/database)


10.install further things:
pip install sqlalchemy psycopg2

11.try first query in jupyter

%load_ext sql

%sql postgresql://postgres:dario2022@localhost/test

%sql SELECT * FROM act_table_full



-- analysis part --

-first part-

12.doing some research (mainly by use of Google) to find out where to find the right attributes to produce a query to select the right data for our analysis.


13.Trial and Error of query on the different tables (57!) of the database.


14.Looking for some hints on the website, where we might find our data out of the tables.


15.This command was very helpful to explore all attributes of all tables within the database: 
%sql SELECT * FROM information_schema.columns WHERE table_schema = 'public' ORDER BY column_name


16.Writing some code in Jupyternotebook to make some queries for our drug.


17.Make some conclusion on the data and Write some code (sql-queries) to extract the right data

18.I have successfully reached our first goal and found the target classes of our chosen Heart diseas drug 'Chlorothiazed'.


-second part-

19.Wrote some more queries to looking for our hyphotesis made

20.I have found one example. Code is found at the end of this notebook.

-third part-
Conclusion and further questions


### From here on you will find the code executed for our project with some hints in advance of the codeblocks

#### Set up part of the project

In [5]:
pip install ipython-sql

In [6]:
pip install sqlalchemy

Note: you may need to restart the kernel to use updated packages.


In [5]:
pip install sqlalchemy psycopg2

Note: you may need to restart the kernel to use updated packages.


In [9]:
import sqlalchemy
a = sqlalchemy.create_engine('postgresql://postgres:dario2022@localhost/test')

In [10]:
%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql


You might change the following codeblock to be able to run the sql-queries which come after them in this notebook

In [12]:
%sql postgresql://postgres:dario2022@localhost/test        

### Drug choice

Drug discovered in the databse of drugs is agains heart problems. It is called Chlorothiazed and has 2 target. For Confrontation I searched again a new drug called Valsartan

### Scientific question

Considering heart diseases is much better having a drugs with more targets, as we see is much better for drug development or is it much better having less? What happen with the side effect?
In addition I want to look for one case, where the following hypothesis is true in some sense:
"The less different target types are found within the targets, the less the probability of having side-effects by using the drug."
"How is it important the number of people who test the drugs?"

#### First part of analysis

This code gave us the possibility to explore the database a little bit since I have not found any class or relation ship diagrams online. I used it to reason about where the data can be found and its possible relations between the exisiting 57 tables.

In [13]:
%sql SELECT * FROM information_schema.columns WHERE table_schema = 'public' ORDER BY column_name

 * postgresql://postgres:***@localhost/test
409 rows affected.


[('test', 'public', 'act_table_full', 'accession', 6, None, 'YES', 'character varying', 1000, 4000, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 'test', 'pg_catalog', 'varchar', None, None, None, None, '6', 'NO', 'NO', None, None, None, None, None, 'NO', 'NEVER', None, 'YES'),
 ('test', 'public', 'target_component', 'accession', 2, None, 'YES', 'character varying', 20, 80, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 'test', 'pg_catalog', 'varchar', None, None, None, None, '2', 'NO', 'NO', None, None, None, None, None, 'NO', 'NEVER', None, 'YES'),
 ('test', 'public', 'pdb', 'accession', 5, None, 'YES', 'character varying', 20, 80, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 'test', 'pg_catalog', 'varchar', None, None, None, None, '5', 'NO', 'NO', None, None, None, None, None, 'NO', 'NEVER', None, 'YES'),
 ('test', 'public', 'act_table_full', 'act_comment', 12, None, 'YES', 'character varying', 1000, 4000, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 'test', 'pg_catalog', 'varchar', None, None, None, None, '12', 'NO', 'NO', None, None, None, None, None, 'NO', 'NEVER', None, 'YES'),
 ('test', 'public', 'act_table_full', 'act_id', 1, None, 'NO', 'integer', None, None, 32, 2, 0, None, None, None, None, None, None, None, None, None, None, None, None, 'test', 'pg_catalog', 'int4', None, None, None, None, '1', 'NO', 'NO', None, None, None, None, None, 'NO', 'NEVER', None, 'YES'),
 ('test', 'public', 'act_table_full', 'act_ref_id', 22, None, 'YES', 'integer', None, None, 32, 2, 0, None, None, None, None, None, None, None, None, None, None, None, None, 'test', 'pg_catalog', 'int4', None, None, None, None, '22', 'NO', 'NO', None, None, None, None, None, 'NO', 'NEVER', None, 'YES'),
 ('test', 'public', 'act_table_full', 'act_source', 13, None, 'YES', 'character varying', 100, 400, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 'test', 'pg_catalog', 'varchar', None, None, None, None, '13', 'NO', 'NO', None, None, None, None, None, 'NO', 'NEVER', None, 'YES'),
 ('test', 'public', 'act_table_full', 'act_source_url', 17, None, 'YES', 'character varying', 500, 2000, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 'test', 'pg_catalog', 'varchar', None, None, None, None, '17', 'NO', 'NO', None, None, None, None, None, 'NO', 'NEVER', None, 'YES'),
 ('test', 'public', 'act_table_full', 'act_type', 11, None, 'YES', 'character varying', 100, 400, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 'test', 'pg_catalog', 'varchar', None, None, None, None, '11', 'NO', 'NO', None, None, None, None, None, 'NO', 'NEVER', None, 'YES'),
 ('test', 'public', 'act_table_full', 'act_unit', 10, None, 'YES', 'character varying', 100, 400, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 'test', 'pg_catalog', 'varchar', None, None, None, None, '10', 'NO', 'NO', None, None, None, None, None, 'NO', 'NEVER', None, 'YES'),
 ('test', 'public', 'act_table_full', 'act_value', 9, None, 'YES', 'double precision', None, None, 53, 2, None, None, None, None, None, None, None, None, None, None, None, None, None, 'test', 'pg_catalog', 'float8', None, None, None, None, '9', 'NO', 'NO', None, None, None, None, None, 'NO', 'NEVER', None, 'YES'),
 ('test', 'public', 'act_table_full', 'action_type', 19, None, 'YES', 'character varying', 50, 200, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 'test', 'pg_catalog', 'varchar', None, None, None, None, '19', 'NO', 'NO', None, None, None, None, None, 'NO', 'NEVER', None, 'YES'),
 ('test', 'public', 'action_type', 'action_type', 2, None, 'NO', 'character varying', 50, 200, None, None, None, None, None, None, None, None, None, None, None, None, None, None, No

With the following code-line I make sure that our drug is found in the database

In [22]:
%sql SELECT * FROM product WHERE product_name = 'Chlorothiazide'

 * postgresql://postgres:***@localhost/test
1 rows affected.


[(2406703, '63323-658', 'INJECTION, POWDER, LYOPHILIZED, FOR SOLUTION', 'CHLOROTHIAZIDE SODIUM', 'Chlorothiazide', 'INTRAVENOUS', 'ANDA', 1)]

The following two queries extract the id/struct_id of the drug to use for further queries

In [23]:
%sql SELECT * FROM synonyms WHERE lname LIKE 'chlorothiazide%'

 * postgresql://postgres:***@localhost/test
2 rows affected.


[(3101, 609, 'chlorothiazide', 1, None, 'chlorothiazide'),
 (13433, 609, 'chlorothiazide sodium', None, None, 'chlorothiazide sodium')]

In [33]:
%sql SELECT DISTINCT id FROM synonyms WHERE lname LIKE 'chlorothiazide%' 

 * postgresql://postgres:***@localhost/test
1 rows affected.


[(609,)]

After I have found the id for Chlorothiazide, which is '609', we are able to extract its target and the target type.

In [25]:
%sql SELECT target_class, COUNT(target_class) FROM act_table_full WHERE struct_id = 609 GROUP BY target_class

 * postgresql://postgres:***@localhost/test
2 rows affected.


[('Enzyme', 1), ('Transporter', 1)]

#### Second part of analysis

Looking for a drug which targets less different target types by trial and error (we used the web GUI of drugcentral.org and searched there with the keyword "heart". With the result generated by the search, I have found that "Valsartan" to have more target types compared to "Chlorothiazed". The queries for this are the same as in the first part:

In [31]:
%sql SELECT * FROM product WHERE product_name = 'Valsartan'

 * postgresql://postgres:***@localhost/test
102 rows affected.


[(2388531, '0781-5607', 'TABLET', 'valsartan', 'Valsartan', 'ORAL', 'NDA AUTHORIZED GENERIC', 1),
 (2388532, '0781-5608', 'TABLET', 'valsartan', 'Valsartan', 'ORAL', 'NDA AUTHORIZED GENERIC', 1),
 (2388533, '0781-5618', 'TABLET', 'valsartan', 'Valsartan', 'ORAL', 'NDA AUTHORIZED GENERIC', 1),
 (2388534, '0781-5619', 'TABLET', 'valsartan', 'Valsartan', 'ORAL', 'NDA AUTHORIZED GENERIC', 1),
 (2389593, '54868-6458', 'TABLET, FILM COATED', 'Valsartan', 'Valsartan', 'ORAL', 'ANDA', 1),
 (2389594, '54868-6452', 'TABLET, FILM COATED', 'Valsartan', 'Valsartan', 'ORAL', 'ANDA', 1),
 (2389595, '54868-6453', 'TABLET, FILM COATED', 'Valsartan', 'Valsartan', 'ORAL', 'ANDA', 1),
 (2389598, '51655-751', 'TABLET, FILM COATED', 'Valsartan', 'Valsartan', 'ORAL', 'ANDA', 1),
 (2390740, '43353-066', 'TABLET', 'valsartan', 'Valsartan', 'ORAL', 'NDA AUTHORIZED GENERIC', 1),
 (2390741, '43353-059', 'TABLET', 'valsartan', 'Valsartan', 'ORAL', 'NDA AUTHORIZED GENERIC', 1),
 (2390742, '43353-067', 'TABLET', 'valsartan', 'Valsartan', 'ORAL', 'NDA AUTHORIZED GENERIC', 1),
 (2393375, '50090-2255', 'TABLET, FILM COATED', 'Valsartan', 'Valsartan', 'ORAL', 'ANDA', 1),
 (2393376, '50090-2433', 'TABLET, FILM COATED', 'Valsartan', 'Valsartan', 'ORAL', 'ANDA', 1),
 (2393377, '50090-2435', 'TABLET, FILM COATED', 'Valsartan', 'Valsartan', 'ORAL', 'ANDA', 1),
 (2393434, '50090-2518', 'TABLET, FILM COATED', 'Valsartan', 'Valsartan', 'ORAL', 'ANDA', 1),
 (2393435, '50090-2550', 'TABLET, FILM COATED', 'Valsartan', 'Valsartan', 'ORAL', 'ANDA', 1),
 (2393436, '50090-2877', 'TABLET, FILM COATED', 'Valsartan', 'Valsartan', 'ORAL', 'ANDA', 1),
 (2393856, '50436-2168', 'TABLET, FILM COATED', 'Valsartan', 'Valsartan', 'ORAL', 'ANDA', 1),
 (2398599, '50090-4293', 'TABLET, FILM COATED', 'Valsartan', 'Valsartan', 'ORAL', 'ANDA', 1),
 (2398607, '50090-4295', 'TABLET, FILM COATED', 'Valsartan', 'Valsartan', 'ORAL', 'ANDA', 1),
 (2398610, '50090-4294', 'TABLET, FILM COATED', 'Valsartan', 'Valsartan', 'ORAL', 'ANDA', 1),
 (2400483, '46708-044', 'TABLET', 'Valsartan', 'Valsartan', 'ORAL', 'ANDA', 1),
 (2400484, '46708-045', 'TABLET', 'Valsartan', 'Valsartan', 'ORAL', 'ANDA', 1),
 (2400485, '46708-046', 'TABLET', 'Valsartan', 'Valsartan', 'ORAL', 'ANDA', 1),
 (2400486, '46708-047', 'TABLET', 'Valsartan', 'Valsartan', 'ORAL', 'ANDA', 1),
 (2401804, '0378-5807', 'TABLET, FILM COATED', 'valsartan', 'Valsartan', 'ORAL', 'ANDA', 1),
 (2401805, '0378-5813', 'TABLET, FILM COATED', 'valsartan', 'Valsartan', 'ORAL', 'ANDA', 1),
 (2401806, '0378-5814', 'TABLET, FILM COATED', 'valsartan', 'Valsartan', 'ORAL', 'ANDA', 1),
 (2401737, '71335-1337', 'TABLET, FILM COATED', 'Valsartan', 'Valsartan', 'ORAL', 'ANDA', 1),
 (2401807, '0378-5815', 'TABLET, FILM COATED', 'valsartan', 'Valsartan', 'ORAL', 'ANDA', 1),
 (2403743, '60687-128', 'TABLET, FILM COATED', 'Valsartan', 'Valsartan', 'ORAL', 'ANDA', 1),
 (2403744, '60687-139', 'TABLET, FILM COATED', 'Valsartan', 'Valsartan', 'ORAL', 'ANDA', 1),
 (2403930, '31722-745', 'TABLET, FILM COATED', 'Valsartan', 'Valsartan', 'ORAL', 'ANDA', 1),
 (2403931, '31722-746', 'TABLET, FILM COATED', 'Valsartan', 'Valsartan', 'ORAL', 'ANDA', 1),
 (2403932, '31722-747', 'TABLET, FILM COATED', 'Valsartan', 'Valsartan', 'ORAL', 'ANDA', 1),
 (2403933, '31722-748', 'TABLET, FILM COATED', 'Valsartan', 'Valsartan', 'ORAL', 'ANDA', 1),
 (2404391, '67877-415', 'TABLET, FILM COATED', 'Valsartan', 'Valsartan', 'ORAL', 'ANDA', 1),
 (2404392, '67877-416', 'TABLET, FILM COATED', 'Valsartan', 'Valsartan', 'ORAL', 'ANDA', 1),
 (2404393, '67877-417', 'TABLET, FILM COATED', 'Valsartan', 'Valsartan', 'ORAL', 'ANDA', 1),
 (2404394, '67877-418', 'TABLET, FILM COATED', 'Valsartan', 'Valsartan', 'ORAL', 'ANDA', 1),
 (2405698, '50268-783', 'TABLET, FILM COATED', 'Valsartan', 'Valsartan', 'ORAL', 'ANDA', 1),
 (2405699, '50268-784', 'TABLET, FILM COATED', 'Valsartan', 'Valsartan', 'ORAL', 'ANDA', 1),
 (2405700, '50268-785', 'TABLET, FILM COATED', 'Valsartan', 'Valsartan', 'ORAL', 'ANDA', 1),
 (24

In [35]:
%sql SELECT * FROM synonyms WHERE lname LIKE 'valsartan%' 

 * postgresql://postgres:***@localhost/test
2 rows affected.


[(1302, 2806, 'valsartanin', None, None, 'valsartanin'),
 (4375, 2806, 'valsartan', 1, None, 'valsartan')]

In [26]:
%sql SELECT DISTINCT id FROM synonyms WHERE lname LIKE 'valsartan%'

 * postgresql://postgres:***@localhost/test
1 rows affected.


[(2806,)]

Pasted the found id from the query before into the next query:

In [27]:
%sql SELECT target_class, COUNT(target_class) FROM act_table_full WHERE struct_id = 2806 GROUP BY target_class

 * postgresql://postgres:***@localhost/test
1 rows affected.


[('GPCR', 4)]

I now compare those two different drugs of its reported sideffects using the table. I can observe that there are far less side effects reported for the first query which represents the drug "Chlorothiazed" (row count: 305 for Chlorothiazed vs. 4341 for Valsartan, and highest likelihood level (llr, 6th column) for "Pyrexia" for example: likelihood level 11.941 for Chlorothiazed vs. 135.939.
Note that I do  not exactly figured which value or ratio is represented exactly with the likelihood ratio numbers provided, nevertheless, the number of reported side effects may state, that there are more side effects found with a drug that has more target types as a target. In fact the Chlorothiazed has only 2 targets, instead Valsartan has 4 targets.
Also note that this is only an assumption and we only found one case which "fullfills" our hypothesis. For further analysis we would look for more confirmations and or negations to better reasono about our hypothesis.
I look for another similar side effects and for "Cardiac failure congestive" the likelihood level is lower for Chrolothiazed than with 6.342 vs Valsartan with 215.783.

In [28]:
%sql SELECT * FROM faers WHERE struct_id = 2806 ORDER BY llr DESC

 * postgresql://postgres:***@localhost/test
4341 rows affected.


[(7424061, 2806, 'Hypotension', 10021097, 'PT', 2144.228, 9.857, 4792, 279481, 465951, 84499266),
 (7015931, 2806, 'Cardiac failure', 10007554, 'PT', 1242.172, 9.857, 2170, 282103, 175700, 84789517),
 (7156413, 2806, 'Dizziness', 10013573, 'PT', 751.535, 9.857, 3847, 280426, 572409, 84392808),
 (8668307, 2806, 'Wrong technique in product usage process', 10076573, 'PT', 633.41, 9.857, 1135, 283138, 93633, 84871584),
 (7390708, 2806, 'Hyperkalaemia', 10020646, 'PT', 628.898, 9.857, 1341, 282932, 125764, 84839453),
 (8211826, 2806, 'Off label use', 10053762, 'PT', 567.355, 9.857, 1042, 283231, 757552, 84207665),
 (6953949, 2806, 'Blood creatinine increased', 10005483, 'PT', 558.988, 9.857, 1600, 282673, 180526, 84784691),
 (8143811, 2806, 'Blood pressure inadequately controlled', 10051128, 'PT', 538.53, 9.857, 332, 283941, 7497, 84957720),
 (6970157, 2806, 'Blood pressure decreased', 10005734, 'PT', 514.147, 9.857, 1146, 283127, 110746, 84854471),
 (8717044, 2806, 'Product prescribing error', 10081770, 'PT', 509.906, 9.857, 667, 283606, 41707, 84923510),
 (6973890, 2806, 'Blood pressure increased', 10005750, 'PT', 495.832, 9.857, 1792, 282481, 228605, 84736612),
 (7078956, 2806, 'Completed suicide', 10010144, 'PT', 449.098, 9.857, 164, 284109, 266570, 84698647),
 (6871810, 2806, 'Angioedema', 10002424, 'PT', 428.577, 9.857, 875, 283398, 79548, 84885669),
 (8124369, 2806, 'Ejection fraction decreased', 10050528, 'PT', 415.81, 9.857, 558, 283715, 35767, 84929450),
 (8601364, 2806, 'Toxicity to various agents', 10070863, 'PT', 397.842, 9.857, 528, 283745, 437929, 84527288),
 (6968525, 2806, 'Blood potassium increased', 10005725, 'PT', 396.646, 9.857, 547, 283726, 35988, 84929229),
 (7018190, 2806, 'Cardiac failure chronic', 10007558, 'PT', 368.306, 9.857, 295, 283978, 10227, 84954990),
 (7596466, 2806, 'Myocardial infarction', 10028596, 'PT', 354.856, 9.857, 1653, 282620, 236327, 84728890),
 (7841457, 2806, 'Rheumatoid arthritis', 10039073, 'PT', 326.227, 9.857, 349, 283924, 318446, 84646771),
 (7400303, 2806, 'Hypertension', 10020772, 'PT', 326.214, 9.857, 2131, 282142, 345903, 84619314),
 (7186126, 2806, 'Dyspnoea', 10013968, 'PT', 322.911, 9.857, 4513, 279760, 901716, 84063501),
 (8448115, 2806, 'Renal impairment', 10062237, 'PT', 312.927, 9.857, 1290, 282983, 174907, 84790310),
 (8580124, 2806, 'Acute kidney injury', 10069339, 'PT', 301.328, 9.857, 3050, 281223, 564065, 84401152),
 (7159780, 2806, 'Drug abuse', 10013654, 'PT', 295.511, 9.857, 78, 284195, 156265, 84808952),
 (7817473, 2806, 'Renal failure', 10038435, 'PT', 273.307, 9.857, 1682, 282591, 267393, 84697824),
 (7628261, 2806, 'Neutropenia', 10029354, 'PT', 271.913, 9.857, 389, 283884, 312783, 84652434),
 (7099213, 2806, 'Cough', 10011224, 'PT', 270.866, 9.857, 2217, 282056, 386385, 84578832),
 (7651835, 2806, 'Oligohydramnios', 10030289, 'PT', 269.66, 9.857, 204, 284069, 6493, 84958724),
 (7932951, 2806, 'Syncope', 10042772, 'PT', 268.396, 9.857, 1368, 282905, 202758, 84762459),
 (7163980, 2806, 'Drug ineffective', 10013709, 'PT', 249.573, 9.857, 2521, 281752, 1138926, 83826291),
 (7419584, 2806, 'Hyponatraemia', 10021036, 'PT', 238.364, 9.857, 1235, 283038, 184198, 84781019),
 (7041268, 2806, 'Cerebrovascular accident', 10008190, 'PT', 238.233, 9.857, 1291, 282982, 195899, 84769318),
 (7305811, 2806, 'Glomerular filtration rate decreased', 10018358, 'PT', 229.196, 9.857, 352, 283921, 25535, 84939682),
 (8163492, 2806, 'Infusion related reaction', 10051792, 'PT', 216.03, 9.857, 156, 284117, 172371, 84792846),
 (7250356, 2806, 'Febrile neutropenia', 10016288, 'PT', 215.99, 9.857, 268, 284005, 228987, 84736230),
 (7018738, 2806, 'Cardiac failure congestive', 10007559, 'PT', 215.783, 9.857, 1193, 283080, 182379, 84782838),
 (8615589, 2806, 'N-terminal prohormone brain natriuretic peptide increased', 10071662, 'PT', 214.038, 9.857, 138, 284135, 3377, 84961840),
 (8533816, 2806, 'Treatment failure', 10066901, 'PT', 208.463, 9.857, 123, 284150, 151291, 84813926),
 (6982291,

In [29]:
%sql SELECT * FROM faers WHERE struct_id = 609 ORDER BY llr DESC

 * postgresql://postgres:***@localhost/test
305 rows affected.


[(7828783, 609, 'Respiratory failure', 10038695, 'PT', 59.794, 23.969, 48, 2311, 208698, 85038433),
 (7782029, 609, 'Pulmonary hypertension', 10037400, 'PT', 53.53, 23.969, 28, 2331, 58587, 85188544),
 (7827583, 609, 'Respiratory distress', 10038687, 'PT', 48.913, 23.969, 28, 2331, 69860, 85177271),
 (8401660, 609, 'Rhinovirus infection', 10061494, 'PT', 48.633, 23.969, 15, 2344, 7917, 85239214),
 (8084335, 609, 'Pulmonary vein stenosis', 10049171, 'PT', 43.015, 23.969, 7, 2352, 193, 85246938),
 (8220422, 609, 'Hospitalisation', 10054112, 'PT', 42.378, 23.969, 31, 2328, 117214, 85129917),
 (7394930, 609, 'Hyperparathyroidism secondary', 10020708, 'PT', 37.175, 23.969, 10, 2349, 3256, 85243875),
 (8503464, 609, 'Pulmonary arterial hypertension', 10064911, 'PT', 34.61, 23.969, 18, 2341, 37152, 85209979),
 (7263274, 609, 'Fluid overload', 10016803, 'PT', 30.093, 23.969, 18, 2341, 48594, 85198537),
 (7431154, 609, 'Hypoxia', 10021143, 'PT', 27.325, 23.969, 23, 2336, 106293, 85140838),
 (8410806, 609, 'Respiratory syncytial virus infection', 10061603, 'PT', 26.552, 23.969, 10, 2349, 9605, 85237526),
 (7673592, 609, 'Oxygen saturation decreased', 10033318, 'PT', 24.591, 23.969, 24, 2335, 134147, 85112984),
 (8349299, 609, 'Cardiac operation', 10061026, 'PT', 23.555, 23.969, 8, 2351, 5711, 85241420),
 (7974497, 609, 'Tracheitis', 10044302, 'PT', 23.205, 23.969, 6, 2353, 1677, 85245454),
 (7424357, 609, 'Hypotension', 10021097, 'PT', 22.789, 23.969, 44, 2315, 470699, 84776432),
 (7031531, 609, 'Catheterisation cardiac', 10007815, 'PT', 22.22, 23.969, 8, 2351, 6775, 85240356),
 (8310039, 609, 'Oxygen consumption increased', 10059168, 'PT', 20.288, 23.969, 7, 2352, 5237, 85241894),
 (6905686, 609, 'Aspartate aminotransferase increased', 10003481, 'PT', 20.269, 23.969, 23, 2336, 152689, 85094442),
 (7214453, 609, 'Enterovirus infection', 10014909, 'PT', 18.925, 23.969, 5, 2354, 1519, 85245612),
 (8277471, 609, 'Transplant evaluation', 10057925, 'PT', 18.22, 23.969, 5, 2354, 1752, 85245379),
 (8075534, 609, 'Gastrostomy', 10048978, 'PT', 18.169, 23.969, 5, 2354, 1770, 85245361),
 (6838991, 609, 'Acute respiratory failure', 10001053, 'PT', 17.925, 23.969, 14, 2345, 58153, 85188978),
 (8583389, 609, 'Use of accessory respiratory muscles', 10069555, 'PT', 16.803, 23.969, 4, 2355, 798, 85246333),
 (7783650, 609, 'Pulmonary oedema', 10037423, 'PT', 16.475, 23.969, 17, 2342, 101375, 85145756),
 (8171475, 609, 'Gastrointestinal hypomotility', 10052105, 'PT', 16.439, 23.969, 5, 2354, 2514, 85244617),
 (7000113, 609, 'Bronchiolitis', 10006448, 'PT', 16.022, 23.969, 6, 2353, 5669, 85241462),
 (6907815, 609, 'Aspiration', 10003504, 'PT', 15.923, 23.969, 9, 2350, 21840, 85225291),
 (8674104, 609, 'Complication associated with device', 10077107, 'PT', 15.664, 23.969, 9, 2350, 22525, 85224606),
 (7349188, 609, 'Heart transplant', 10019314, 'PT', 15.252, 23.969, 4, 2355, 1181, 85245950),
 (7186424, 609, 'Dyspnoea', 10013968, 'PT', 15.099, 23.969, 57, 2302, 906172, 84340959),
 (8017186, 609, 'Viral infection', 10047461, 'PT', 15.035, 23.969, 12, 2347, 51401, 85195730),
 (8623500, 609, 'Refractory cytopenia with unilineage dysplasia', 10072684, 'PT', 14.773, 23.969, 4, 2355, 1333, 85245798),
 (8250188, 609, 'Abdominal infection', 10056519, 'PT', 14.362, 23.969, 5, 2354, 3840, 85243291),
 (8580422, 609, 'Acute kidney injury', 10069339, 'PT', 14.205, 23.969, 41, 2318, 567074, 84680057),
 (8402206, 609, 'Serratia infection', 10061512, 'PT', 13.63, 23.969, 4, 2355, 1781, 85245350),
 (6850614, 609, 'Alanine aminotransferase increased', 10001551, 'PT', 13.108, 23.969, 20, 2339, 176715, 85070416),
 (7345339, 609, 'Heart disease congenital', 10019273, 'PT', 13.078, 23.969, 5, 2354, 4997, 85242134),
 (7385498, 609, 'Hypercalciuria', 10020590, 'PT', 12.751, 23.969, 3, 2356, 569, 85246562),
 (6955653, 609, 'Blood culture positive', 10005488, 'PT', 12.72, 23.969, 6, 2353, 10034, 85237097),
 (7846420, 609, 'Right ventricular failure', 10039163, 'PT', 12.164, 23.969, 8

In [30]:
%sql SELECT struct_id, meddra_name, llr FROM faers WHERE struct_id = 2806 AND meddra_name = 'Pyrexia' UNION SELECT struct_id, meddra_name, llr FROM faers WHERE struct_id = 609 AND meddra_name = 'Pyrexia' ORDER BY LLR DESC

 * postgresql://postgres:***@localhost/test
2 rows affected.


[(2806, 'Pyrexia', 135.393), (609, 'Pyrexia', 11.941)]

In [34]:
%sql SELECT struct_id, meddra_name, llr FROM faers WHERE struct_id = 2806 AND meddra_name = 'Cardiac failure congestive' UNION SELECT struct_id, meddra_name, llr FROM faers WHERE struct_id = 609 AND meddra_name = 'Cardiac failure congestive' ORDER BY LLR DESC

 * postgresql://postgres:***@localhost/test
2 rows affected.


[(2806, 'Cardiac failure congestive', 215.783),
 (609, 'Cardiac failure congestive', 6.342)]

## third part

Looking at the other numbers we can see that for the side effect "Pyrexia", for the second drugs there way more people who did not have side effect. This means, I think, that the second drugs is more effective than Chlorothiazed. In contrast having more side effect (4135 vs 305) is not good for a drugs, but the number of people who had side effect in percentile is way less for the varsavan then the chlorothiazed.

https://drugcentral.org/drugcard/609?q=heart

https://drugcentral.org/drugcard/2806?q=heart